# Generated by Django 3.1.5 on 2021-01-30 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Email', models.CharField(max_length=100)),
                ('email_Email', models.EmailField(max_length=100)),
                ('message_Email', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Storage_Estiment', models.BooleanField(default=False)),
                ('Home_Move_Estiment', models.BooleanField(default=False)),
                ('Donation_Estiment', models.BooleanField(default=False)),
                ('Junk_Estiment', models.BooleanField(default=False)),
                ('Pickups_Estiment', models.BooleanField(default=False)),
                ('Craiglist_Estiment', models.BooleanField(default=False)),
                ('pickup', models.BooleanField(default=False)),
                ('ten_truck', models.BooleanField(default=False)),
                ('fifteen_truck', models.BooleanField(default=False)),
                ('seventeen_truck', models.BooleanField(default=False)),
                ('twenty_truck', models.BooleanField(default=False)),
                ('twenty_six_truck', models.BooleanField(default=False)),
                ('one_peolpe', models.BooleanField(default=False)),
                ('two_people', models.BooleanField(default=False)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('details', models.CharField(max_length=255)),
                ('book_service', models.CharField(max_length=255)),
                ('book_truck', models.CharField(max_length=255)),
                ('book_crew', models.CharField(max_length=255)),
            ],
        ),
    ]
